export const DESTINATION_INFO: Record<string, { name: string; description: string; image: string }> = {
  Greece: {
    name: "Greece",
    image: "/src/assets/destinations/greece.jpg",
    description: `Greece is a Mediterranean country known for its ancient history, stunning islands, and vibrant culture. With over 6,000 islands, Greece offers pristine beaches, crystal-clear waters, and world-class hospitality.\n\nTop attractions include the Acropolis in Athens, the whitewashed villages of Santorini, and the ancient ruins of Delphi. The Greek islands are perfect for island hopping, with Mykonos, Crete, and Rhodes being popular destinations.\n\nVisit in the spring (April-May) or fall (September-October) for the best weather. The summer months are hot but perfect for beach lovers. Greek cuisine is Mediterranean at its best, featuring fresh seafood, olive oil, and feta cheese.\n\nDon't miss the sunset at Santorini, the tavernas of Mykonos, or the archaeological wonders scattered throughout the country. Greece offers the perfect blend of history, nature, and modern hospitality.`,
  },
  Japan: {
    name: "Japan",
    image: "/src/assets/destinations/japan.jpg",
    description: `Japan is a fascinating blend of ancient traditions and cutting-edge modernity. From the temples of Kyoto to the neon lights of Tokyo, Japan offers visitors an unforgettable experience.\n\nTokyo is the energetic capital filled with shopping, entertainment, and amazing restaurants. Kyoto showcases traditional architecture and beautiful gardens. The peaceful temples and Zen gardens make it perfect for spiritual travelers.\n\nSpring brings stunning cherry blossoms, while autumn offers vibrant fall foliage. Mount Fuji is Japan's iconic natural landmark and can be visited year-round. The Japanese Alps offer hiking opportunities and mountain scenery.\n\nJapanese cuisine is world-famous, from sushi and ramen to tempura and sake. Experience traditional tea ceremonies, visit ancient shrines, or relax in natural hot springs. The efficiency and cleanliness of Japanese cities will amaze you.\n\nBest time to visit is spring (March-May) or fall (September-November). Japan's public transportation is excellent, making travel between cities easy and affordable.`,
  },
  Rome: {
    name: "Rome",
    image: "/src/assets/destinations/rome.jpg",
    description: `Rome, the Eternal City, is one of the world's most romantic and historically significant destinations. This ancient capital is home to countless monuments, museums, and piazzas.\n\nThe Colosseum stands as a testament to Roman engineering and power. The Vatican City houses the breathtaking St. Peter's Basilica and the Sistine Chapel. The Roman Forum reveals the remains of ancient temples and government buildings.\n\nToss a coin in the Trevi Fountain to ensure your return to Rome. Climb the Spanish Steps for panoramic views. Explore the cobblestone streets and discover hidden piazzas around every corner.\n\nRome's cuisine is authentic Italian at its best - pasta, pizza, risotto, and gelato. Visit local trattorias for genuine Roman dishes. The coffee culture is exceptional, with espresso being a way of life.\n\nWander through charming neighborhoods like Trastevere with its ivy-covered buildings and cozy restaurants. The city is perfect for leisurely walks, museum visits, and enjoying Italian dolce vita lifestyle.`,
  },
  Morocco: {
    name: "Morocco",
    image: "/src/assets/destinations/morocco.jpg",
    description: `Morocco is an exotic North African country blending Arab, Berber, and French influences. From the Atlas Mountains to the Sahara Desert, Morocco offers diverse landscapes and rich cultural experiences.\n\nMarrakech is the vibrant heart of Morocco with bustling medinas and colorful souks. Fez is known for its ancient medina and traditional leather tanneries. The blue city of Chefchaouen captivates visitors with its entirely blue buildings.\n\nThe Sahara Desert offers camel trekking and desert camps under starlit skies. The Atlantic coastal towns of Essaouira combine beach relaxation with cultural exploration. Trekking in the Atlas Mountains rewards adventurers with stunning views.\n\nMoroccan cuisine is aromatic and flavorful - tagines, couscous, and mint tea are staples. Experience traditional hammams and rejuvenating spa treatments. The hospitality of Moroccan people is warm and welcoming.\n\nBest time to visit is October-April when temperatures are moderate. Respect local customs and dress modestly in religious areas. Learn basic French or Arabic phrases to enhance your interactions with locals.`,
  },
  Vietnam: {
    name: "Vietnam",
    image: "/src/assets/destinations/vietnam.jpg",
    description: `Vietnam is a Southeast Asian gem stretching along the coast with diverse landscapes from mountains to river deltas. This country offers incredible food, ancient temples, and vibrant cities.\n\nHanoi, the capital, is a bustling city with French colonial architecture and a thriving street food scene. Ho Chi Minh City (Saigon) is modern and energetic with war history museums and contemporary art. Hue is the ancient imperial city with historical significance.\n\nHalong Bay is a UNESCO World Heritage Site famous for its limestone karsts and emerald waters. Cruise through the bay for unforgettable views. Visit the floating villages to experience local fishing communities.\n\nSapa in the north offers stunning trekking with terraced rice fields. The Mekong Delta in the south is lush and agricultural, perfect for boat tours. Hoi An is a charming ancient town with lantern-lit streets and tailoring shops.\n\nVietnamese cuisine is considered one of the world's best - pho, banh mi, fresh spring rolls, and seafood are delicious. The country is affordable and welcoming. Best time to visit is September-April.`,
  },
  Phuket: {
    name: "Phuket",
    image: "/src/assets/destinations/phuket.jpg",
    description: `Phuket is Thailand's largest island and a premier beach destination in Southeast Asia. Known for pristine beaches, water sports, and vibrant nightlife, Phuket attracts millions of visitors yearly.\n\nPatong Beach is the most popular beach with water sports, jet skiing, and parasailing. Karon Beach and Kata Beach are quieter alternatives with family-friendly atmospheres. The beaches offer stunning sunsets and warm, clear waters year-round.\n\nThe Old Town of Phuket showcases Sino-Portuguese architecture and authentic local culture. Visit Big Buddha for panoramic island views. Explore the Big Lagoon and scenic viewpoints.\n\nWater activities include snorkeling, scuba diving in nearby islands like Phi Phi, and island hopping tours. The Andaman Sea offers excellent diving opportunities with coral reefs and marine life.\n\nPhuket's food scene is exceptional - fresh seafood, Thai curries, and street food. Enjoy traditional Thai massage and spa treatments. The island never sleeps with numerous bars, clubs, and restaurants.\n\nBest time to visit is November-April for dry weather. Stay hydrated in the tropical heat. Mix beach relaxation with adventure activities for a complete Phuket experience.`,
  },
  Barcelona: {
    name: "Barcelona",
    image: "/src/assets/destinations/barcelona.jpg",
    description: `Barcelona is Spain's most vibrant city, famous for unique architecture, Mediterranean beaches, and dynamic culture. The capital of Catalonia seamlessly blends history with modernity.\n\nSagrada Familia is Gaudí's masterpiece - a spectacular basilica under construction for over a century. Park Güell offers whimsical views of the city with Gaudí's artistic touches. Casa Batlló showcases innovative modernist architecture.\n\nThe Gothic Quarter features medieval streets, ancient Roman walls, and charming plazas. La Rambla is a famous tree-lined boulevard bustling with performers and cafes. The beaches provide perfect relaxation after city exploration.\n\nBarcelona is a sports city - visit Camp Nou to see FC Barcelona's stadium. The city's nightlife is legendary with clubs, tapas bars, and rooftop lounges. Montjuïc hill offers museums, gardens, and city views.\n\nCatalan cuisine is delicious - try pa amb tomàquet (bread with tomato), seafood paella, and cava (sparkling wine). The city is walkable with excellent public transportation. Best time to visit is September-November or March-May.`,
  },
  "Sri Lanka": {
    name: "Sri Lanka",
    image: "/src/assets/destinations/sri-lanka.jpg",
    description: `Sri Lanka, the "Pearl of the Indian Ocean," is an island nation offering diverse experiences - mountains, beaches, temples, and wildlife in a compact area.\n\nColombo is the bustling capital with colonial architecture and modern development. Kandy, nestled in mountains, houses the sacred Temple of the Tooth Relic. Galle is a charming coastal town with Portuguese-era fortifications.\n\nThe central highlands offer tea plantations and scenic train rides. Visit tea factories and learn about Ceylon tea production. The misty mountains provide trekking opportunities and breathtaking views.\n\nSri Lankan beaches are world-class - Mirissa, Unawatuna, and Arugambe offer sand, surfing, and serenity. Yala National Park offers wildlife safaris to spot leopards, elephants, and crocodiles.\n\nThe culture is deeply spiritual with numerous Buddhist temples, Hindu shrines, and pilgrimage sites. Adam's Peak (Sri Pada) offers a sacred mountain climb with rewarding sunrise views.\n\nSri Lankan cuisine is flavorful with curries, rice dishes, and tropical fruits. The country is affordable and welcoming. Best time to visit varies by region - generally December-March for southern coast.`,
  },
};
